[project]
name = "diplom"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "flask>=3.1.0",
    "joblib>=1.4.2",
    "numpy==2.1.3",
    "scikit-learn>=1.6.1",
    "tensorflow>=2.19.0",
]
